/* Desafio Nesta aula construímos um relatório que apresentou os clientes que tiveram vendas inválidas.
Vendas inválidas é aquele que comprou mais do que seu limite permitido por mês, igual o pessoal da coca..
*/
-- Relatório de Vendas Válidas

SELECT * FROM itens_notas_fiscais;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM tabela_de_clientes;

-- Consulta com vendas de clientes por mês 
SELECT NF.CPF, DATE_FORMAT(NF.DATA_VENDA, "%M/%Y") AS MES_ANO, SUM(QUANTIDADE) AS QUANTIDADE_VENDA
  FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY CPF, MES_ANO;


-- LIMITE DE COMPRA POR CLIENTE

SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE	
  FROM TABELA_DE_CLIENTES TC;
  
  
-- result

SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, "%M/%Y") AS MES_ANO, 
SUM(QUANTIDADE) AS QUANTIDADE_VENDA,
TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE
  FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON TC.CPF = NF.CPF
GROUP BY CPF, MES_ANO;

SELECT*FROM tabela_de_clientes;



-- COM SUBCONSULTA, calculando a diferença
SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDA, X.QUANTIDADE_LIMITE,
X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDA AS DIFERENÇA
FROM (
SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, "%M/%Y") AS MES_ANO, 
SUM(QUANTIDADE) AS QUANTIDADE_VENDA,
TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE
  FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON TC.CPF = NF.CPF
GROUP BY CPF, MES_ANO) X;


-- com case

SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDA, X.QUANTIDADE_LIMITE,
X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDA AS DIFERENÇA, -- Com o case feito nós podemos ocultar a diferença, depende de como o cliente deseja
CASE
  WHEN (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDA) < 0 THEN "Inválido" -- NÃO USEI O AS DIFERENÇA POIS O BD IDENTIFICA ELE COMO COLUNA
  ELSE "Válido"
END AS STATUS_VENDA
FROM (
SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, "%M/%Y") AS MES_ANO, 
SUM(QUANTIDADE) AS QUANTIDADE_VENDA,
TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE
  FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON TC.CPF = NF.CPF
GROUP BY CPF, MES_ANO) X;